/**
 * THE 5 FUNDAMENTAL CONCEPTS OF PROGRAMMING
 * Canonical Terms & Definitions Reference
 * 5 Concepts. Every Language. Every Programmer.
 */

export const CONCEPTS = [
  {
    id: 'take-input',
    num: '01',
    term: 'Take Input',
    category: 'COMMUNICATION & INGESTION',
    color: '#00F0FF',
    textColor: '#000000',
    iconName: 'Keyboard',
    definition: 'The program listens before it acts.',
    formalDef: 'Input allows a system to consume external data—from keyboard events, mouse clicks, network packets, or file streams—so runtime state can dynamically react.',
    progression: 'Keyboard Event → File Stream → API Payload',
    snippets: [
      { lang: 'Java', code: 'Scanner scanner = new Scanner(System.in);\nString val = scanner.nextLine();' },
      { lang: 'C#', code: 'string input = Console.ReadLine();\nint num = int.Parse(input);' },
      { lang: 'JavaScript', code: 'const input = prompt("Enter value:");\nprocess.stdin.on("data", chunk => {});' },
      { lang: 'Python', code: 'val = input("Enter value: ")\nraw = sys.stdin.read()' },
    ],
    properties: [
      { label: 'LISTEN', desc: 'Program halts execution or subscribes to events waiting for external input.' },
      { label: 'BUFFER', desc: 'Raw input streams are captured in system buffers prior to type conversion.' },
      { label: 'PARSE', desc: 'Converts raw string data into typed integers, floats, or structured payloads.' },
      { label: 'VALIDATE', desc: 'Sanitizes and verifies input boundaries before executing downstream logic.' },
    ],
    examples: [
      { name: 'Console Read', complexity: 'Standard In' },
      { name: 'File Streams', complexity: 'Disk I/O' },
      { name: 'DOM Events', complexity: 'UI Listener' },
      { name: 'HTTP Payloads', complexity: 'Network I/O' },
    ],
    codeLines: [
      { n: 1, text: '// 1. Program listens before it acts',           key: 'LISTEN' },
      { n: 2, text: 'String raw = Console.ReadLine(); // C#',           key: 'BUFFER' },
      { n: 3, text: 'Scanner sc = new Scanner(System.in); // Java',    key: 'LISTEN' },
      { n: 4, text: '',                                                  key: null },
      { n: 5, text: '// 2. Parse & Validate input string',             key: 'PARSE' },
      { n: 6, text: 'int limit = Integer.parseInt(raw);',              key: 'VALIDATE' },
    ],
  },
  {
    id: 'allocate-memory',
    num: '02',
    term: 'Allocate Memory',
    category: 'STATE MANAGEMENT & STORAGE',
    color: '#00E599',
    textColor: '#000000',
    iconName: 'Box',
    definition: 'Store what you learn — from simple values to complex structures.',
    formalDef: 'Memory allocation reserves address space in RAM (Stack or Heap) to store state, evolving from primitive scalar values into composite objects, trees, and linked lists.',
    progression: 'Primitives (int, string) → Objects → Trees & Lists',
    snippets: [
      { lang: 'Java', code: 'int count = 42;\nList<String> items = new ArrayList<>();' },
      { lang: 'C#', code: 'int score = 100;\nvar tree = new Dictionary<string, Node>();' },
      { lang: 'JavaScript', code: 'let val = 42;\nconst obj = { key: "value", items: [1, 2] };' },
      { lang: 'Python', code: 'count = 42\ndata = {"users": [1, 2, 3]}' },
    ],
    properties: [
      { label: 'STACK vs HEAP', desc: 'Primitives reside on fast call stack; complex reference objects live on heap.' },
      { label: 'PRIMITIVES', desc: 'Atomic scalar types: Integers, Floats, Booleans, and Characters.' },
      { label: 'OBJECTS & MAPS', desc: 'Key-value associative groupings representing entity state.' },
      { label: 'TREES & LISTS', desc: 'Dynamic pointer-linked data structures scaling to arbitrary lengths.' },
    ],
    examples: [
      { name: 'Primitives', complexity: 'Stack Slot' },
      { name: 'Objects', complexity: 'Heap Memory' },
      { name: 'Arrays & Lists', complexity: 'Contiguous' },
      { name: 'Trees & Graphs', complexity: 'Pointer Nodes' },
    ],
    codeLines: [
      { n: 1, text: '// Primitive stack allocation',                  key: 'PRIMITIVES' },
      { n: 2, text: 'int limit = 100; // Java / C# primitive',          key: 'STACK vs HEAP' },
      { n: 3, text: 'string flag = "ACTIVE";',                          key: 'PRIMITIVES' },
      { n: 4, text: '',                                                  key: null },
      { n: 5, text: '// Heap composite structure allocation',           key: 'OBJECTS & MAPS' },
      { n: 6, text: 'var map = new HashMap<String, Integer>();',        key: 'TREES & LISTS' },
      { n: 7, text: 'map.put("limit", limit);',                         key: 'OBJECTS & MAPS' },
    ],
  },
  {
    id: 'give-output',
    num: '03',
    term: 'Give Output',
    category: 'PRESENTATION & RENDERING',
    color: '#0038FF',
    textColor: '#FFFFFF',
    iconName: 'Monitor',
    definition: 'Turn raw results into something humans can actually read.',
    formalDef: 'Output translates internal state and calculated values into human-readable representations—ranging from raw stdout text streams to formatted tabular reports and visual dashboards.',
    progression: 'Console text → Tables → Dashboards',
    snippets: [
      { lang: 'Java', code: 'System.out.println("Result: " + val);\nSystem.out.printf("%-10s %d%n", name, val);' },
      { lang: 'C#', code: 'Console.WriteLine($"Result: {val}");\nConsole.Table(results);' },
      { lang: 'JavaScript', code: 'console.log("Result:", val);\nconsole.table([{ id: 1, text: "Fizz" }]);' },
      { lang: 'Python', code: 'print(f"Result: {val}")\nprint(tabulate(data, headers="firstrow"))' },
    ],
    properties: [
      { label: 'CONSOLE STDOUT', desc: 'Sequential stream writing to standard output stream.' },
      { label: 'FORMATTED TABLES', desc: 'Structured grid rendering aligning columns and headers.' },
      { label: 'DASHBOARDS', desc: 'Visual UI elements, charts, and real-time canvas updates.' },
      { label: 'ENCODING', desc: 'Converting binary state to UTF-8 text or visual pixels.' },
    ],
    examples: [
      { name: 'Console Log', complexity: 'stdout' },
      { name: 'Tabular Grid', complexity: 'Formatted' },
      { name: 'UI Dashboard', complexity: 'GUI / Canvas' },
      { name: 'JSON API', complexity: 'REST Payload' },
    ],
    codeLines: [
      { n: 1, text: '// 1. Console Text Output',                        key: 'CONSOLE STDOUT' },
      { n: 2, text: 'System.out.println("Starting computation...");',   key: 'CONSOLE STDOUT' },
      { n: 3, text: '',                                                  key: null },
      { n: 4, text: '// 2. Tabular Format Output',                      key: 'FORMATTED TABLES' },
      { n: 5, text: 'Console.WriteLine(string.Format("{0,-10} {1}", "NUM", "RESULT"));', key: 'FORMATTED TABLES' },
      { n: 6, text: '',                                                  key: null },
      { n: 7, text: '// 3. Dashboard UI Render',                        key: 'DASHBOARDS' },
      { n: 8, text: 'renderDashboardGrid(results);',                    key: 'DASHBOARDS' },
    ],
  },
  {
    id: 'make-decisions',
    num: '04',
    term: 'Make Decisions',
    category: 'CONDITIONAL LOGIC & BRANCHING',
    color: '#FF2A00',
    textColor: '#FFFFFF',
    iconName: 'GitFork',
    definition: 'If this, then that. The logic that drives every program.',
    formalDef: 'Decision statements evaluate boolean predicate expressions to select between alternative execution pathways, branching program flow based on dynamic conditions.',
    progression: 'if / else → ternary operators → nested logic',
    snippets: [
      { lang: 'Java', code: 'if (i % 15 == 0) {\n    return "FizzBuzz";\n} else if (i % 3 == 0) {\n    return "Fizz";\n}' },
      { lang: 'C#', code: 'string res = (i % 15 == 0) ? "FizzBuzz" : (i % 3 == 0) ? "Fizz" : i.ToString();' },
      { lang: 'JavaScript', code: 'const tag = (n % 15 === 0) ? "FizzBuzz" : (n % 3 === 0) ? "Fizz" : n;' },
      { lang: 'Python', code: 'if n % 15 == 0:\n    res = "FizzBuzz"\nelif n % 3 == 0:\n    res = "Fizz"' },
    ],
    properties: [
      { label: 'SELECTION', desc: 'Evaluating boolean truths to execute specific code blocks.' },
      { label: 'IF / ELSE', desc: 'Primary dual-branch conditional construct.' },
      { label: 'TERNARY', desc: 'Compact inline conditional expression: (condition ? true : false).' },
      { label: 'NESTED LOGIC', desc: 'Cascading decision trees for multi-condition evaluations.' },
    ],
    examples: [
      { name: 'if / else', complexity: 'Binary Branch' },
      { name: 'ternary (?:)', complexity: 'Inline Select' },
      { name: 'switch / match', complexity: 'Multi-Way' },
      { name: 'Predicate Logic', complexity: 'Boolean Algebra' },
    ],
    codeLines: [
      { n: 1, text: '// Binary Decision Branch',                       key: 'IF / ELSE' },
      { n: 2, text: 'if (number % 15 == 0) {',                           key: 'SELECTION' },
      { n: 3, text: '    output = "FizzBuzz";',                          key: 'SELECTION' },
      { n: 4, text: '} else if (number % 3 == 0) {',                     key: 'NESTED LOGIC' },
      { n: 5, text: '    output = "Fizz";',                              key: 'NESTED LOGIC' },
      { n: 6, text: '} else {',                                          key: 'IF / ELSE' },
      { n: 7, text: '    output = String.valueOf(number);',             key: 'IF / ELSE' },
      { n: 8, text: '}',                                                 key: null },
      { n: 9, text: '// Inline Ternary Operator',                      key: 'TERNARY' },
      { n: 10, text: 'String tag = (n % 5 == 0) ? "Buzz" : "Num";',     key: 'TERNARY' },
    ],
  },
  {
    id: 'loop',
    num: '05',
    term: 'Loop',
    category: 'ITERATION & REPETITION',
    color: '#FFE600',
    textColor: '#000000',
    iconName: 'RotateCw',
    definition: 'Repeat the work so you don\'t have to.',
    formalDef: 'Looping constructs continuously repeat a sequence of instructions while a termination condition remains true, automating iteration across data series.',
    progression: 'for → while → foreach',
    snippets: [
      { lang: 'Java', code: 'for (int i = 1; i <= 100; i++) {\n    process(i);\n}' },
      { lang: 'C#', code: 'foreach (var item in collection) {\n    Console.WriteLine(item);\n}' },
      { lang: 'JavaScript', code: 'for (let i = 1; i <= 100; i++) {\n    console.log(i);\n}' },
      { lang: 'Python', code: 'for i in range(1, 101):\n    print(i)' },
    ],
    properties: [
      { label: 'FOR LOOP', desc: 'Deterministic counter-driven loop with explicit init, condition, and step.' },
      { label: 'WHILE LOOP', desc: 'Indefinite loop executing while a boolean condition evaluates true.' },
      { label: 'FOREACH', desc: 'High-level iterator abstracting array/collection traversal.' },
      { label: 'TERMINATION', desc: 'Guaranteed exit condition preventing infinite execution loops.' },
    ],
    examples: [
      { name: 'for (i=1; i<=100; i++)', complexity: 'Counter Loop' },
      { name: 'while (condition)', complexity: 'Predicate Loop' },
      { name: 'foreach (x in list)', complexity: 'Iterator' },
      { name: 'Recursion', complexity: 'Functional Loop' },
    ],
    codeLines: [
      { n: 1, text: '// Deterministic For Loop (1 to 100)',            key: 'FOR LOOP' },
      { n: 2, text: 'for (int i = 1; i <= 100; i++) {',                  key: 'FOR LOOP' },
      { n: 3, text: '    processNumber(i);',                             key: 'FOR LOOP' },
      { n: 4, text: '}',                                                 key: null },
      { n: 5, text: '',                                                  key: null },
      { n: 6, text: '// Collection Iterator (Foreach)',                 key: 'FOREACH' },
      { n: 7, text: 'foreach (var item in numbersList) {',               key: 'FOREACH' },
      { n: 8, text: '    Console.WriteLine(item);',                      key: 'FOREACH' },
      { n: 9, text: '}',                                                 key: 'TERMINATION' },
    ],
  },
];
