/**
 * THE 8 FUNDAMENTAL CONCEPTS OF ALGORITHMS
 * Canonical Terms & Definitions Reference
 * This is the single source of truth for the entire infographic.
 */

export const CONCEPTS = [
  {
    id: 'algorithm',
    num: '01',
    term: 'Algorithm',
    category: 'FOUNDATION',
    color: '#00F0FF',
    textColor: '#000000',
    definition: 'A finite, unambiguous sequence of well-defined instructions that transforms specified inputs into specified outputs and is guaranteed to terminate.',
    formalDef: 'An algorithm A is a finite set of instructions such that: (1) each instruction is clear and unambiguous, (2) there exists at least one input, (3) there exist one or more outputs, (4) it terminates after a finite number of steps, (5) every operation is feasible.',
    properties: [
      { label: 'FINITE', desc: 'Must terminate after a finite number of steps — the halting guarantee.' },
      { label: 'DEFINITE', desc: 'Every step is precisely and unambiguously specified.' },
      { label: 'INPUT/OUTPUT', desc: 'Has well-defined inputs and produces defined outputs.' },
      { label: 'EFFECTIVE', desc: 'Every operation must be feasible and executable.' },
    ],
    examples: [
      { name: 'Euclidean GCD', complexity: 'O(log min(a,b))' },
      { name: "Dijkstra's Shortest Path", complexity: 'O((V+E) log V)' },
      { name: 'Binary Search', complexity: 'O(log n)' },
      { name: 'RSA Key Generation', complexity: 'O(k³)' },
    ],
    codeLines: [
      { n: 1, text: 'function gcd(a, b) {',          key: null },
      { n: 2, text: '  while (b !== 0) {',            key: 'FINITE' },
      { n: 3, text: '    let r = a % b;',             key: 'DEFINITE' },
      { n: 4, text: '    a = b;  b = r;',             key: 'DEFINITE' },
      { n: 5, text: '  }',                            key: null },
      { n: 6, text: '  return a; // ← OUTPUT',        key: 'INPUT/OUTPUT' },
      { n: 7, text: '}',                              key: null },
    ],
  },
  {
    id: 'data-structure',
    num: '02',
    term: 'Data Structure',
    category: 'MEMORY & ORGANIZATION',
    color: '#00E599',
    textColor: '#000000',
    definition: 'A specialized format for organizing, storing, and accessing data in memory that exposes a defined set of operations with specific time and space trade-offs.',
    formalDef: 'A data structure D = (S, Ops) where S is a storage schema (contiguous, pointer-linked, hash-indexed, or hierarchical) and Ops is a set of operations each with an asymptotic cost characterizing the access vs. mutation trade-off.',
    properties: [
      { label: 'LAYOUT', desc: 'Contiguous (cache-friendly) vs pointer-linked (dynamic) vs hash-indexed (O(1) avg).' },
      { label: 'ACCESS COST', desc: 'The asymptotic cost to retrieve any single element.' },
      { label: 'MUTATION COST', desc: 'Insert and Delete costs — often in tension with access speed.' },
      { label: 'SPACE', desc: 'Total memory consumed: payload + overhead (pointers, padding, capacity).' },
    ],
    tradeoffs: [
      { name: 'Array',          access: 'O(1)',        insert: 'O(n)',        del: 'O(n)',       space: 'O(n)',   color: '#00F0FF' },
      { name: 'Linked List',    access: 'O(n)',        insert: 'O(1)*',      del: 'O(1)*',     space: 'O(n)',   color: '#00E599' },
      { name: 'Hash Map',       access: 'O(1) avg',   insert: 'O(1) avg',   del: 'O(1) avg',  space: 'O(n)',   color: '#FFE600' },
      { name: 'Binary Heap',    access: 'O(1) top',   insert: 'O(log n)',   del: 'O(log n)',   space: 'O(n)',   color: '#7928CA' },
      { name: 'BST (balanced)', access: 'O(log n)',   insert: 'O(log n)',   del: 'O(log n)',   space: 'O(n)',   color: '#FF2A00' },
    ],
    examples: [
      { name: 'Contiguous Array', complexity: 'O(1) access' },
      { name: 'Linked List', complexity: 'O(1) insert at head' },
      { name: 'Hash Table', complexity: 'O(1) avg lookup' },
      { name: 'Binary Heap (PQ)', complexity: 'O(log n) extract-min' },
    ],
    codeLines: [
      { n: 1, text: 'class Node {',                              key: 'LAYOUT' },
      { n: 2, text: '  constructor(val) {',                     key: null },
      { n: 3, text: '    this.val = val;   // payload',         key: 'SPACE' },
      { n: 4, text: '    this.next = null; // pointer (+8B)',    key: 'SPACE' },
      { n: 5, text: '  }',                                      key: null },
      { n: 6, text: '}',                                        key: null },
      { n: 7, text: '// Access: O(n) — must traverse chain',    key: 'ACCESS COST' },
      { n: 8, text: '// Insert head: O(1) — pointer swap only', key: 'MUTATION COST' },
    ],
  },
  {
    id: 'time-complexity',
    num: '03',
    term: 'Time Complexity',
    category: 'COMPLEXITY ANALYSIS',
    color: '#FFE600',
    textColor: '#000000',
    definition: 'A function T(n) that counts the number of elementary operations executed by an algorithm as input size n grows, evaluated asymptotically to classify worst-, average-, and best-case behavior.',
    formalDef: 'Let T(n) be the count of elementary operations (comparisons, assignments, arithmetic) for input of size n. Time complexity classifies T(n) under three regimes: worst-case O(n), average-case Θ(n), and best-case Ω(n) — all independent of CPU clock speed.',
    properties: [
      { label: 'T(n) FUNCTION', desc: 'The exact operation count as a mathematical function of input size n.' },
      { label: 'HARDWARE-INDEPENDENT', desc: 'Counts logical operations, not clock cycles — universally comparable.' },
      { label: 'THREE CASES', desc: 'Best (Ω), Average (Θ), and Worst (O) — all three matter for analysis.' },
      { label: 'ASYMPTOTIC', desc: 'Dominant term wins as n→∞; constants and lower-order terms are dropped.' },
    ],
    scalingRows: [
      { label: 'O(1) — Constant',       fn: () => 1,                            color: '#00E599', tier: 'OPTIMAL'      },
      { label: 'O(log n) — Logarithmic', fn: n => Math.ceil(Math.log2(n)),       color: '#00F0FF', tier: 'EXCELLENT'    },
      { label: 'O(n) — Linear',          fn: n => n,                             color: '#FFE600', tier: 'GOOD'         },
      { label: 'O(n log n) — Linearithmic', fn: n => Math.ceil(n*Math.log2(n)), color: '#0038FF', tier: 'ACCEPTABLE'   },
      { label: 'O(n²) — Quadratic',      fn: n => n*n,                           color: '#FF2A00', tier: 'POOR'         },
      { label: 'O(2ⁿ) — Exponential',   fn: n => Math.pow(2, Math.min(n,20)),   color: '#7928CA', tier: 'CATASTROPHIC' },
    ],
    examples: [
      { name: 'Array index access',  complexity: 'O(1)' },
      { name: 'Binary Search',       complexity: 'O(log n)' },
      { name: 'Linear scan',         complexity: 'O(n)' },
      { name: 'Bubble Sort',         complexity: 'O(n²)' },
    ],
    codeLines: [
      { n: 1, text: 'function findMax(arr) {',                   key: null },
      { n: 2, text: '  let max = arr[0];        // T(1)',        key: 'T(n) FUNCTION' },
      { n: 3, text: '  for (let i=1; i<n; i++) // T(n-1)',      key: 'T(n) FUNCTION' },
      { n: 4, text: '    if (arr[i] > max)      // T(n-1) cmps', key: 'THREE CASES' },
      { n: 5, text: '      max = arr[i];',                       key: null },
      { n: 6, text: '  return max;',                             key: null },
      { n: 7, text: '} // Total T(n) = c·n  ⟹  O(n)',          key: 'ASYMPTOTIC' },
    ],
  },
  {
    id: 'space-complexity',
    num: '04',
    term: 'Space Complexity',
    category: 'COMPLEXITY ANALYSIS',
    color: '#FF0055',
    textColor: '#FFFFFF',
    definition: 'A function S(n) = Input Space + Auxiliary Space that measures the total memory an algorithm requires to execute, as a function of input size n.',
    formalDef: 'S(n) = S_input(n) + S_aux(n). Input space is the memory for parameters. Auxiliary space is the extra memory: local variables, dynamic buffers, and recursive call-stack frames. In-place algorithms achieve S_aux = O(1).',
    properties: [
      { label: 'INPUT SPACE', desc: 'Memory occupied by the input data itself — often unavoidable.' },
      { label: 'AUXILIARY SPACE', desc: 'Extra memory allocated by the algorithm: the metric engineers optimize.' },
      { label: 'CALL STACK DEPTH', desc: 'Recursive functions consume O(depth) frames on the execution stack.' },
      { label: 'IN-PLACE', desc: 'An algorithm is in-place if S_aux = O(1) — it reuses input memory.' },
    ],
    memoryModes: [
      { label: 'In-Place O(1)',     aux: 1,   desc: 'Reuses input memory. Only a handful of register variables.', color: '#00E599', example: 'Insertion Sort, Bubble Sort' },
      { label: 'Log-Stack O(log n)',aux: 13,  desc: 'QuickSort recursion: call stack depth = log n frames.',      color: '#FFE600', example: 'QuickSort (average case)' },
      { label: 'Linear O(n)',       aux: 100, desc: 'Merge Sort allocates a full duplicate n-element buffer.',     color: '#FF2A00', example: 'Merge Sort, HashMap init' },
    ],
    examples: [
      { name: 'Insertion Sort (in-place)', complexity: 'O(1) aux' },
      { name: 'QuickSort recursion stack', complexity: 'O(log n) aux' },
      { name: 'Merge Sort merge buffer',   complexity: 'O(n) aux' },
      { name: 'Floyd-Warshall matrix',     complexity: 'O(n²) aux' },
    ],
    codeLines: [
      { n: 1, text: '// S(n) = Input + Auxiliary',               key: null },
      { n: 2, text: 'function inPlace(arr) {       // O(1)',      key: 'IN-PLACE' },
      { n: 3, text: '  let tmp;   // ← 1 variable, O(1)',        key: 'AUXILIARY SPACE' },
      { n: 4, text: '  // mutates arr directly — no copy',        key: 'INPUT SPACE' },
      { n: 5, text: '}',                                          key: null },
      { n: 6, text: 'function clone(arr) {         // O(n)',      key: null },
      { n: 7, text: '  return [...arr]; // ← n extra cells',      key: 'AUXILIARY SPACE' },
      { n: 8, text: '}                  // S_aux = O(n)',         key: 'AUXILIARY SPACE' },
    ],
  },
  {
    id: 'big-o',
    num: '05',
    term: 'Big O Notation',
    category: 'ASYMPTOTIC THEORY',
    color: '#0038FF',
    textColor: '#FFFFFF',
    definition: 'A mathematical notation that classifies algorithms by their worst-case asymptotic upper bound, formally: f(n) = O(g(n)) iff ∃ constants c > 0 and n₀ > 0 such that f(n) ≤ c · g(n) for all n ≥ n₀.',
    formalDef: 'Big-O bounds from above. Big-Omega Ω bounds from below (best case). Big-Theta Θ bounds both above and below (tight bound). Drop all constant coefficients and lower-order terms: 5n² + 100n + 8 → O(n²).',
    properties: [
      { label: 'UPPER BOUND', desc: 'O(g(n)) guarantees f(n) never exceeds c·g(n) beyond n₀.' },
      { label: 'DROP CONSTANTS', desc: 'O(5n) = O(n). Constants are hardware artifacts, not algorithmic.' },
      { label: 'DROP LOW-ORDER', desc: 'O(n² + n) = O(n²). As n→∞, low-order terms become negligible.' },
      { label: 'THREE NOTATIONS', desc: 'O (worst), Ω (best), Θ (tight) — together characterize all cases.' },
    ],
    notations: [
      { symbol: 'O',  name: 'Big-Oh',    bound: 'Upper',  caseLabel: 'Worst Case',   color: '#FF2A00', formal: 'f(n) ≤ c·g(n), ∀n ≥ n₀' },
      { symbol: 'Θ',  name: 'Big-Theta', bound: 'Tight',  caseLabel: 'Average Case', color: '#FFE600', formal: 'c₁·g(n) ≤ f(n) ≤ c₂·g(n)' },
      { symbol: 'Ω',  name: 'Big-Omega', bound: 'Lower',  caseLabel: 'Best Case',    color: '#00E599', formal: 'f(n) ≥ c·g(n), ∀n ≥ n₀' },
    ],
    examples: [
      { name: 'O(1)   Hash map lookup',    complexity: 'CONSTANT' },
      { name: 'O(log n) Binary search',    complexity: 'LOGARITHMIC' },
      { name: 'O(n log n) Merge Sort',     complexity: 'LINEARITHMIC' },
      { name: 'O(2ⁿ) Power set',           complexity: 'EXPONENTIAL' },
    ],
    codeLines: [
      { n: 1, text: '// f(n) = 3n² + 50n + 1000',              key: null },
      { n: 2, text: '// Step 1: Identify dominant term → n²',   key: 'DROP LOW-ORDER' },
      { n: 3, text: '// Step 2: Drop coefficient → n²',         key: 'DROP CONSTANTS' },
      { n: 4, text: '// Step 3: Verify upper bound:',           key: 'UPPER BOUND' },
      { n: 5, text: '//   ∃ c=4, n₀=100 s.t. f(n) ≤ 4·n²',    key: 'UPPER BOUND' },
      { n: 6, text: '// ∴ f(n) = O(n²)  ✓',                    key: 'THREE NOTATIONS' },
    ],
  },
  {
    id: 'recursion',
    num: '06',
    term: 'Recursion',
    category: 'ALGORITHMIC PARADIGM',
    color: '#7928CA',
    textColor: '#FFFFFF',
    definition: 'A technique where a function solves a problem by calling itself on a strictly smaller subproblem, progressing toward a base case that terminates the self-calls and returns an explicit value.',
    formalDef: 'A recursive algorithm R must satisfy: (1) BASE CASE — a condition under which R returns a result without any self-call; (2) RECURSIVE STEP — R calls itself with strictly reduced input, guaranteed to reach the base case. Each call pushes a frame onto the LIFO call stack.',
    properties: [
      { label: 'BASE CASE', desc: 'The termination condition — returns a value without any recursive call.' },
      { label: 'RECURSIVE STEP', desc: 'Calls itself with strictly smaller input, moving toward the base case.' },
      { label: 'CALL STACK (LIFO)', desc: 'Each call pushes a frame; base case triggers unwinding in reverse.' },
      { label: 'STACK DEPTH', desc: 'Maximum simultaneous frames = recursion depth. Overflow if no base case.' },
    ],
    stackSteps: [
      { frame: 'factorial(4)', phase: 'PUSH', highlight: 'RECURSIVE STEP', note: 'n=4 > 1 → call factorial(3)' },
      { frame: 'factorial(3)', phase: 'PUSH', highlight: 'RECURSIVE STEP', note: 'n=3 > 1 → call factorial(2)' },
      { frame: 'factorial(2)', phase: 'PUSH', highlight: 'RECURSIVE STEP', note: 'n=2 > 1 → call factorial(1)' },
      { frame: 'factorial(1)', phase: 'BASE', highlight: 'BASE CASE',      note: 'n=1 ≤ 1 → return 1  ← BASE CASE HIT' },
      { frame: 'factorial(2)', phase: 'POP',  highlight: 'CALL STACK (LIFO)', note: 'Unwind: 2 × 1 = 2 → return 2' },
      { frame: 'factorial(3)', phase: 'POP',  highlight: 'CALL STACK (LIFO)', note: 'Unwind: 3 × 2 = 6 → return 6' },
      { frame: 'factorial(4)', phase: 'POP',  highlight: 'CALL STACK (LIFO)', note: 'Unwind: 4 × 6 = 24 → return 24 ✓' },
    ],
    examples: [
      { name: 'Factorial n!',          complexity: 'O(n) time, O(n) stack' },
      { name: 'Fibonacci (memoized)',   complexity: 'O(n) time, O(n) stack' },
      { name: 'Tree DFS traversal',    complexity: 'O(n) time, O(h) stack' },
      { name: 'Tower of Hanoi',        complexity: 'O(2ⁿ) time, O(n) stack' },
    ],
    codeLines: [
      { n: 1, text: 'function factorial(n) {',              key: null },
      { n: 2, text: '  if (n <= 1) return 1; // BASE CASE', key: 'BASE CASE' },
      { n: 3, text: '  // ↑ terminates — no self-call',     key: 'BASE CASE' },
      { n: 4, text: '',                                      key: null },
      { n: 5, text: '  return n * factorial(n - 1);',       key: 'RECURSIVE STEP' },
      { n: 6, text: '  // ↑ n-1 < n — strictly smaller',   key: 'RECURSIVE STEP' },
      { n: 7, text: '}  // each call → 1 STACK FRAME',      key: 'CALL STACK (LIFO)' },
    ],
  },
  {
    id: 'divide-conquer',
    num: '07',
    term: 'Divide & Conquer',
    category: 'ALGORITHMIC PARADIGM',
    color: '#FF2A00',
    textColor: '#FFFFFF',
    definition: 'A top-down design paradigm that recursively partitions a problem into non-overlapping sub-problems of equal size, solves each independently, and combines their results into the master solution.',
    formalDef: 'A D&C algorithm follows 3 phases: (1) DIVIDE — split input of size n into b sub-problems of size n/b; (2) CONQUER — solve each sub-problem recursively (or directly if trivial); (3) COMBINE — merge sub-solutions in O(f(n)) time. Recurrence: T(n) = a·T(n/b) + f(n) → Master Theorem.',
    properties: [
      { label: 'DIVIDE', desc: 'Partition the problem into b non-overlapping sub-problems of size n/b.' },
      { label: 'CONQUER', desc: 'Recursively solve each sub-problem until it reaches the trivial base case.' },
      { label: 'COMBINE', desc: 'Merge the b sub-solutions into the complete answer for size n.' },
      { label: 'MASTER THEOREM', desc: 'T(n) = a·T(n/b) + f(n) determines recurrence complexity analytically.' },
    ],
    phases: [
      {
        id: 'divide',
        label: '① DIVIDE',
        color: '#FF2A00',
        desc: 'Split array [38,27,43,3,9,82,10] at midpoint into two halves.',
        visual: ['38','27','43','3','|','9','82','10'],
        sub: 'Problem size: n → n/2 per recursive branch',
      },
      {
        id: 'conquer',
        label: '② CONQUER',
        color: '#FFE600',
        desc: 'Recursively sort each half until sub-arrays of size 1 (trivially sorted).',
        visual: ['[3,27,38,43]','[9,10,82]'],
        sub: 'Base case: array.length ≤ 1 → already sorted',
      },
      {
        id: 'combine',
        label: '③ COMBINE',
        color: '#00E599',
        desc: 'Merge the two sorted halves into the final sorted array in O(n) time.',
        visual: ['3','9','10','27','38','43','82'],
        sub: 'Merge operation: scan both arrays once → O(n)',
      },
    ],
    examples: [
      { name: 'Merge Sort',            complexity: 'O(n log n)' },
      { name: 'Quick Sort',            complexity: 'O(n log n) avg' },
      { name: 'Binary Search',         complexity: 'O(log n)' },
      { name: 'Karatsuba Multiply',    complexity: 'O(n^1.585)' },
    ],
    codeLines: [
      { n: 1, text: 'function mergeSort(arr) {',                    key: null },
      { n: 2, text: '  if (arr.length<=1) return arr; // base case', key: 'CONQUER' },
      { n: 3, text: '  const mid = arr.length >> 1;',               key: 'DIVIDE' },
      { n: 4, text: '  const L = mergeSort(arr.slice(0,mid));',     key: 'DIVIDE' },
      { n: 5, text: '  const R = mergeSort(arr.slice(mid));',       key: 'DIVIDE' },
      { n: 6, text: '  return merge(L, R);',                        key: 'COMBINE' },
      { n: 7, text: '} // T(n)=2T(n/2)+O(n) → O(n log n)',         key: 'MASTER THEOREM' },
    ],
  },
  {
    id: 'brute-force',
    num: '08',
    term: 'Brute Force',
    category: 'ALGORITHMIC PARADIGM',
    color: '#FF6B00',
    textColor: '#FFFFFF',
    definition: 'A problem-solving strategy that exhaustively enumerates every possible candidate solution in the search space, evaluating each against the desired criterion, guaranteed correct if the space is finite.',
    formalDef: 'Brute Force: for each x in S (the complete search space), test predicate P(x); return x if P(x) = true. Correctness is guaranteed by completeness. Cost is |S|: Ω(n) for linear search, Ω(n²) for pair search, Ω(2ⁿ) for subset search, Ω(n!) for permutation search.',
    properties: [
      { label: 'EXHAUSTIVE', desc: 'Every candidate in the search space S is evaluated — none skipped.' },
      { label: 'GUARANTEED CORRECT', desc: 'Completeness ensures the answer is found if it exists in S.' },
      { label: 'NO HEURISTICS', desc: 'No domain knowledge, pruning, or mathematical shortcuts applied.' },
      { label: 'COMBINATORIAL COST', desc: '|S| grows combinatorially: n, n², 2ⁿ, or n! with problem type.' },
    ],
    searchSpaces: [
      { label: 'Linear Search',       space: 'n elements',           complexity: 'O(n)',   example: 'Find target in unsorted array' },
      { label: 'Pair Comparison',     space: 'n² pairs',             complexity: 'O(n²)',  example: 'All duplicate pairs in array' },
      { label: 'Subset Enumeration',  space: '2ⁿ subsets',           complexity: 'O(2ⁿ)', example: 'Knapsack brute force' },
      { label: 'Permutation Search',  space: 'n! routes',            complexity: 'O(n!)',  example: 'Brute-force Traveling Salesperson' },
    ],
    examples: [
      { name: 'Linear Search',                complexity: 'O(n)' },
      { name: 'Naive String Match',           complexity: 'O(n·m)' },
      { name: 'Exhaustive Subset Search',     complexity: 'O(2ⁿ)' },
      { name: 'Brute-force TSP',              complexity: 'O(n!)' },
    ],
    codeLines: [
      { n: 1, text: 'function bruteSearch(arr, target) {',  key: null },
      { n: 2, text: '  // Enumerate EVERY index:',          key: 'EXHAUSTIVE' },
      { n: 3, text: '  for (let i=0; i<arr.length; i++) {', key: 'EXHAUSTIVE' },
      { n: 4, text: '    if (arr[i] === target)',            key: 'GUARANTEED CORRECT' },
      { n: 5, text: '      return i; // found it',          key: 'GUARANTEED CORRECT' },
      { n: 6, text: '  }',                                  key: null },
      { n: 7, text: '  return -1; // scanned all n → O(n)', key: 'COMBINATORIAL COST' },
      { n: 8, text: '} // NO pruning, NO shortcuts',        key: 'NO HEURISTICS' },
    ],
  },
];
