/**
 * THE 5 FUNDAMENTAL CONCEPTS OF PROGRAMMING
 * Canonical Terms & Definitions Reference
 * Based on: Basics of Computer Programming (Mimo)
 */

export const CONCEPTS = [
  {
    id: 'variables',
    num: '01',
    term: 'Variables & Constants',
    category: 'STATE MANAGEMENT',
    color: '#00F0FF',
    textColor: '#000000',
    definition: 'Named storage locations in memory used to hold data that can either change (variables) or remain fixed (constants) during program execution.',
    formalDef: 'A variable is an abstract storage location paired with an associated symbolic name, which contains some known or unknown quantity of information referred to as a value. A constant is a variable whose value cannot be altered once assigned.',
    properties: [
      { label: 'DECLARATION', desc: 'Reserves memory space and associates it with an identifier (name).' },
      { label: 'ASSIGNMENT', desc: 'Stores a specific value into the allocated memory space.' },
      { label: 'MUTABILITY', desc: 'Variables can be updated; constants (const) are immutable.' },
      { label: 'SCOPE', desc: 'The region of code where the identifier is visible and accessible.' },
    ],
    examples: [
      { name: 'age = 25', complexity: 'Mutable' },
      { name: 'PI = 3.14', complexity: 'Immutable' },
      { name: 'name = "Sarah"', complexity: 'String' },
    ],
    codeLines: [
      { n: 1, text: '# Variable: value can change',            key: 'MUTABILITY' },
      { n: 2, text: 'age = 25     # ← DECLARE & ASSIGN',       key: 'DECLARATION' },
      { n: 3, text: 'name = "Sarah"',                          key: 'ASSIGNMENT' },
      { n: 4, text: '',                                        key: null },
      { n: 5, text: 'age = 26     # Happy birthday!',          key: 'MUTABILITY' },
      { n: 6, text: '',                                        key: null },
      { n: 7, text: 'PI = 3.14    # Constant (by convention)', key: 'DECLARATION' },
    ],
    // Custom data for the visualizer
    memorySlots: [
      { label: 'age', type: 'let', val: 25, canChange: true },
      { label: 'name', type: 'let', val: '"Alice"', canChange: true },
      { label: 'GRAVITY', type: 'const', val: 9.81, canChange: false },
    ]
  },
  {
    id: 'data-types',
    num: '02',
    term: 'Data Types',
    category: 'INFORMATION REPRESENTATION',
    color: '#00E599',
    textColor: '#000000',
    definition: 'Classifications that specify which type of value a variable has and what type of mathematical, relational or logical operations can be applied to it.',
    formalDef: 'A data type is an attribute of data which tells the compiler or interpreter how the programmer intends to use the data. It defines the operations that can be done on the data, the meaning of the data, and the way values of that type can be stored.',
    properties: [
      { label: 'PRIMITIVES', desc: 'Basic types: Numbers, Strings, Booleans, Null, Undefined.' },
      { label: 'COMPOSITES', desc: 'Complex types: Arrays, Objects, Structs, Classes.' },
      { label: 'TYPE CHECKING', desc: 'Can be Static (at compile time) or Dynamic (at runtime).' },
      { label: 'COERCION', desc: 'Implicit conversion of one data type into another.' },
    ],
    typesList: [
      { name: 'Integer',     val: '42',        desc: 'Whole numbers without a fractional component.', color: '#00F0FF' },
      { name: 'Float',       val: '3.14159',   desc: 'Numbers with a fractional (decimal) component.', color: '#00E599' },
      { name: 'String',      val: '"Hello!"',  desc: 'A sequence of characters used to represent text.', color: '#FFE600' },
      { name: 'Boolean',     val: 'true',      desc: 'Logical values representing truth (true) or falsehood (false).', color: '#7928CA' },
      { name: 'Array/List',  val: '[1, 2, 3]', desc: 'An ordered collection of values accessed by index.', color: '#FF2A00' },
    ],
    examples: [
      { name: 'Integer/Float', complexity: 'Numeric' },
      { name: 'String', complexity: 'Text' },
      { name: 'Boolean', complexity: 'Logic' },
      { name: 'Object', complexity: 'Key-Value' },
    ],
    codeLines: [
      { n: 1, text: 'count = 42              # Integer',       key: 'PRIMITIVES' },
      { n: 2, text: 'pi = 3.14               # Float',         key: 'PRIMITIVES' },
      { n: 3, text: 'msg = "Hello World"     # String',        key: 'PRIMITIVES' },
      { n: 4, text: 'is_active = True        # Boolean',       key: 'PRIMITIVES' },
      { n: 5, text: '',                                        key: null },
      { n: 6, text: 'data = [1, 2, 3]        # List/Array',    key: 'COMPOSITES' },
      { n: 7, text: 'p = {"x": 10, "y": 5}   # Dictionary',    key: 'COMPOSITES' },
      { n: 8, text: '',                                        key: null },
      { n: 9, text: 'res = str(5) + "2"      # Coercion',      key: 'COERCION' },
    ],
  },
  {
    id: 'control-structures',
    num: '03',
    term: 'Control Structures',
    category: 'EXECUTION FLOW',
    color: '#FFE600',
    textColor: '#000000',
    definition: 'Blocks of code that alter the sequential execution of a program by introducing decision making, branching, and repetition.',
    formalDef: 'Control flow statements specify the order in which individual statements, instructions or function calls are executed. The primary forms are Sequence (default), Selection (if/else, switch), and Iteration (for, while, do-while loops).',
    properties: [
      { label: 'CONDITIONALS', desc: 'Branching logic (if/else) based on boolean expressions.' },
      { label: 'LOOPS', desc: 'Repeating a block of code (for/while) until a condition is met.' },
      { label: 'ITERATION', desc: 'Stepping through a collection or array of items.' },
      { label: 'BRANCHING', desc: 'Jumping to a different part of the program.' },
    ],
    examples: [
      { name: 'if / else', complexity: 'Selection' },
      { name: 'for loop', complexity: 'Iteration' },
      { name: 'while loop', complexity: 'Iteration' },
      { name: 'switch', complexity: 'Branching' },
    ],
    codeLines: [
      { n: 1, text: '# Conditional Logic',                      key: 'CONDITIONALS' },
      { n: 2, text: 'if temperature > 30:',                     key: 'CONDITIONALS' },
      { n: 3, text: '    print("It\'s hot outside!")',          key: 'BRANCHING' },
      { n: 4, text: 'else:',                                    key: 'CONDITIONALS' },
      { n: 5, text: '    print("The weather is pleasant.")',    key: 'BRANCHING' },
      { n: 6, text: '',                                         key: null },
      { n: 7, text: '# Repetition (Loop)',                      key: 'LOOPS' },
      { n: 8, text: 'for i in range(1, 4):',                    key: 'ITERATION' },
      { n: 9, text: '    print(i)',                             key: 'LOOPS' },
    ],
  },
  {
    id: 'input-output',
    num: '04',
    term: 'Input/Output (I/O)',
    category: 'COMMUNICATION',
    color: '#FF0055',
    textColor: '#FFFFFF',
    definition: 'The methods by which a program receives data from the outside world (Input) and sends data back to the outside world (Output).',
    formalDef: 'I/O refers to the communication between an information processing system, such as a computer, and the outside world, possibly a human or another information processing system. Inputs are the signals or data received by the system and outputs are the signals or data sent from it.',
    properties: [
      { label: 'INPUT', desc: 'Data from keyboards, mice, files, sensors, or network requests.' },
      { label: 'OUTPUT', desc: 'Data to screens, files, speakers, motors, or network responses.' },
      { label: 'ASYNCHRONOUS', desc: 'I/O operations often take time, requiring callbacks or promises.' },
      { label: 'PARSING', desc: 'Translating raw input strings into usable data types (e.g. JSON to Object).' },
    ],
    examples: [
      { name: 'prompt() / alert()', complexity: 'UI I/O' },
      { name: 'fetch()', complexity: 'Network I/O' },
      { name: 'fs.readFile()', complexity: 'File I/O' },
      { name: 'console.log()', complexity: 'Standard Out' },
    ],
    codeLines: [
      { n: 1, text: '# 1. Receive Input',                       key: 'INPUT' },
      { n: 2, text: 'raw_input = input("Enter age:")',          key: 'INPUT' },
      { n: 3, text: '',                                         key: null },
      { n: 4, text: '# 2. Parse & Process',                     key: 'PARSING' },
      { n: 5, text: 'age = int(raw_input)',                     key: 'PARSING' },
      { n: 6, text: 'next_year = age + 1',                      key: null },
      { n: 7, text: '',                                         key: null },
      { n: 8, text: '# 3. Produce Output',                      key: 'OUTPUT' },
      { n: 9, text: 'print(f"You will be {next_year}")',        key: 'OUTPUT' },
    ],
  },
  {
    id: 'functions',
    num: '05',
    term: 'Functions',
    category: 'MODULARITY',
    color: '#0038FF',
    textColor: '#FFFFFF',
    definition: 'Reusable blocks of code designed to perform a particular task. They receive inputs (arguments), process them, and return an output.',
    formalDef: 'A subroutine, function, procedure, or routine is a sequence of program instructions that performs a specific task, packaged as a unit. Functions encapsulate logic, take parameters, prevent code duplication (DRY), and return values to the caller.',
    properties: [
      { label: 'PARAMETERS', desc: 'Placeholders for the inputs a function expects to receive.' },
      { label: 'ARGUMENTS', desc: 'The actual values passed into the function when it is called.' },
      { label: 'RETURN VALUE', desc: 'The final result that the function passes back to the caller.' },
      { label: 'REUSABILITY', desc: 'Write once, call many times. Keeps code DRY (Don\'t Repeat Yourself).' },
    ],
    examples: [
      { name: 'function add(a,b)', complexity: 'Declaration' },
      { name: 'const add = (a,b) =>', complexity: 'Arrow Function' },
      { name: 'Math.max(1, 5)', complexity: 'Built-in Call' },
      { name: 'array.map(fn)', complexity: 'Higher-Order' },
    ],
    codeLines: [
      { n: 1, text: '# Define function with parameters',        key: 'PARAMETERS' },
      { n: 2, text: 'def calculate_area(length, width):',       key: 'PARAMETERS' },
      { n: 3, text: '    return length * width',                key: 'RETURN VALUE' },
      { n: 4, text: '',                                         key: null },
      { n: 5, text: '# Call function with arguments',           key: 'ARGUMENTS' },
      { n: 6, text: 'room_area = calculate_area(10, 12)',       key: 'ARGUMENTS' },
      { n: 7, text: 'print(room_area)',                         key: 'REUSABILITY' },
    ],
  },
];
